# CCSpace Archive Configuration

# Source folder (downloaded archive)
archive_dir: archive

# Destination folder for published site
publish_dir: docs

# New content folder (markdown files and images)
new_content_dir: newContent
